name: flutter_telpo
description: A flutter plugin for Telpo TPS320 POS. This plugin only handles the ability of the device to communicate with the it thermal printer. 
version: 0.0.3
homepage: https://github.com/efikas/telpo.git
repository: https://github.com/efikas/telpo

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  plugin:
    platforms:
      android:
        package: com.efikas.telpo
        pluginClass: FlutterTelpoPlugin
  #

 